apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
    - name: todoapp
      image: yevgene/todoapp:3.0.0
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /liveness
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 20
